// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDORxh9OgzkCtB9UApxek5f_ohXTZ0zgiA',
    appId: '1:553864015162:web:0ce0a62352d31198eaf403',
    messagingSenderId: '553864015162',
    projectId: 'fir-project-204c7',
    authDomain: 'fir-project-204c7.firebaseapp.com',
    storageBucket: 'fir-project-204c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCizGJNWzDUcdrxfdv870_b5tDaGIqi184',
    appId: '1:553864015162:android:9ad1e0edd867a99eeaf403',
    messagingSenderId: '553864015162',
    projectId: 'fir-project-204c7',
    storageBucket: 'fir-project-204c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA098JgguojwFpz-HhLb9zTnXOLqsGusRE',
    appId: '1:553864015162:ios:521aba68f21bbfa5eaf403',
    messagingSenderId: '553864015162',
    projectId: 'fir-project-204c7',
    storageBucket: 'fir-project-204c7.firebasestorage.app',
    iosBundleId: 'com.example.machinTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDORxh9OgzkCtB9UApxek5f_ohXTZ0zgiA',
    appId: '1:553864015162:web:f2fa6bd6e4f095caeaf403',
    messagingSenderId: '553864015162',
    projectId: 'fir-project-204c7',
    authDomain: 'fir-project-204c7.firebaseapp.com',
    storageBucket: 'fir-project-204c7.firebasestorage.app',
  );
}
