// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuMnQJGcQgqlCnN_G8Y8d99N4fzM1Jt5w',
    appId: '1:7027983878:web:24506bdca9233b9b096587',
    messagingSenderId: '7027983878',
    projectId: 'machintask-ad831',
    authDomain: 'machintask-ad831.firebaseapp.com',
    storageBucket: 'machintask-ad831.firebasestorage.app',
    measurementId: 'G-1M7BF3HM28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATjmkAXxyA7abxw0fN_CBUowoLp0BGD7I',
    appId: '1:7027983878:android:3417735b4ff19ee6096587',
    messagingSenderId: '7027983878',
    projectId: 'machintask-ad831',
    storageBucket: 'machintask-ad831.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo-QCZ3IHIWrm3RBfXKAwd55HRaiNjX0k',
    appId: '1:7027983878:ios:a210f73c40c73837096587',
    messagingSenderId: '7027983878',
    projectId: 'machintask-ad831',
    storageBucket: 'machintask-ad831.firebasestorage.app',
    iosBundleId: 'com.example.machinTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuMnQJGcQgqlCnN_G8Y8d99N4fzM1Jt5w',
    appId: '1:7027983878:web:fb240be4800b895f096587',
    messagingSenderId: '7027983878',
    projectId: 'machintask-ad831',
    authDomain: 'machintask-ad831.firebaseapp.com',
    storageBucket: 'machintask-ad831.firebasestorage.app',
    measurementId: 'G-0ER04SFZKW',
  );

}